name             'php_environment'
maintainer       'PhpVagrantMulti'
maintainer_email 'phpvagrantmulti@gmail.com'
license          'GPL v3'
description      'Installs/Configures the php environment'
long_description 'Installs/Configures the php environment'
version          '0.4.1'
depends          'mysql', '~> 8.0'
